name: Markdown lint

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'restqa-404-links'
      uses: restqa/404-links@2.2.0
      with:
          comment_tag_name: "YOUTUBE-VIDEOS-LIST"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=vq2jYFZVMDA"
