name: YouTube Video
on:
 schedule:
    #Runs every hour
    -cron: '0 * * * *'
 workflow_dispatch:
 
 jobs: 
  youtube:
 name: video from YouYube
 rusn-on: ubuntu-latest
 steps:
 -uses: actions/chekoutv2
 with: 
 comment_tag_name: "YOUTUBE-VIDEO"
 feed_list: "https://youtube.com/feeds/videos.xml?channel_id=vq2jYFZVMDA"
